[package]
name = "cortex-m-switch"
version = "0.1.0"
authors = ["Daan de Graaf <daandegraaf9@gmail.com>"]
edition = "2018"

[dependencies]
cortex-m-switch-macros = { path = "macros" }
cortex-m-rt = "0.6.7"
cortex-m = "0.5.8"
arrayvec = { version = "0.4.10", default-features = false }
